### ISSUE TITLE
How to use on Google Chrome?

### ISSUE THREAD

**Issue by Marco70cn** [openhardwarecoza/LaserWeb3#206]
I tried every suggestion found on the web, but seem like i can't find the right solution. Starting with cmd file,  can't find the localhost.
Also installed GIT, but changed nothing.
If directly i try to open the index.html, can see the first page but of course can't use.
i use W10 64bit, Chrome Version 55.0.2883.87 m

Any suggestion?

**Comment by openhardwarecoza** [comment]
Works for the other 600+ users who read github.com/LaserWeb/LaserWeb3/wiki
and followed the install instructions...  Read it and follow exactly

On Dec 22, 2016 7:03 AM, "Marco70cn" <notifications@github.com> wrote:

I tried every suggestion found on the web, but seem like i can't find the
right solution. Starting with cmd file, can't find the localhost.
Also installed GIT, but changed nothing.
If directly i try to open the index.html, can see the first page but of
course can't use.
i use W10 64bit, Chrome Version 55.0.2883.87 m

Any suggestion?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LaserWeb/LaserWeb3/issues/206>, or mute the thread

**Comment by ghost** [comment]
https://github.com/LaserWeb/LaserWeb3/wiki/Install:-Windows
