### ISSUE TITLE
Negative Zoom?

### ISSUE THREAD

**Issue by emteeoh** [openhardwarecoza/LaserWeb3#67]
If you keep zooming in on the origin, at some point the entire image flips and then starts to zoom out. Before and after flip screenshots attached.
![screenshot from 2016-08-02 19 40 37](https://cloud.githubusercontent.com/assets/756072/17349099/29364c84-58e9-11e6-9056-c798a7c083e4.png)
![screenshot from 2016-08-02 19 40 50](https://cloud.githubusercontent.com/assets/756072/17349103/2cfcdeaa-58e9-11e6-81f3-e1b845355694.png)

**Comment by ghost** [comment]
Thats because when you zoom in past zero,  your camera now sits behind thw
grid.  And the camera will always face the user.  Thus,  to do that,  the
camera,  now behind the bed,  has to look back at you,  through he rear of
the bed.

Ie totally normal.  Just dont scroll that far.   I wont remove negative
camera positions since thats useful for inspection of the bottom of for
example cnc toolpaths (tools,  options,  cnc cam)

**Comment by emteeoh** [comment]
It hadn't occurred to me that it was useful!
